default: &default
  adapter:  postgresql
  encoding: unicode
  host:     localhost
  username: postgres
  password: root

development:
  <<: *default
  darabase: minesweeper_game_development


test:
  <<: *default
  darabase: minesweeper_game_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>

